---
- name: Ensure Apache is installed
  yum: name=httpd state=present

- name: Initialize Apache
  service: name=httpd state=started enabled=yes
  notify:
  - Restart Apache
- name: Copy Site Files
  template: src=templates/index.j2 dest={{ doc_root }}/index.html
